name: 'Orq Actions'
description: "Don't use this action directly."
author: 'Orq'
runs:
  using: 'composite'
  steps:
    - name: 'Warning'
      run: |
        echo "Don't use this action directly."
        exit 1
      shell: bash
