name: 'Orq test experiment'
description: 'Automatically run experiment on your project using Orq'
author: 'haroldorquesta'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  api_key:
    description: Orq api key
    required: true
  path:
    description: Yaml config path
    required: true

# Define your outputs here.
# outputs:
#   time:
#     description: Your output description here

runs:
  using: node20
  main: dist/index.js
